### ISSUE TITLE
Support Roslyn analyzer

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/CSharpCompilerSettingsForUnity#9]
- [x] The analyzer package will be extracted to `Library` directory
  * No need to install `dotnet` or `nuget`
  * The analyzer dlls are not referenced by Unity as assets
- [x] Configure settings in `Project Settings` window
  - [x] Choose analyzer packages (name and version)
  - [x] Filter assemblies to analyze
- [x] The analyzer dlls and rulesets will be referenced in the response file for the compilation process
  * `Temp/UnityTempFile-***`
- [x] Support IDE
- [ ] Support all platforms
  - [ ] Windows
  - [x] macOS
  - [x] Linux

**Comment by KuraiAndras** [comment]
How do you plan on implementing this?

**Comment by mob-sakai** [comment]
Basically, it will be implemented as follows.
https://docs.unity3d.com/2020.2/Documentation/Manual/roslyn-analyzers.html

* Add the following to the response file used for the compiler process:

```
/analyzer: "path/to/analyzer"
/ruleset: "path/to/ruleset"
```

### Different points:

* No need to reload the ruleset file
* An analyzer package will be installed automatically
* Specify the name of the assembly you want to analyze (or a regular expression)
* Option to treat analysis errors as compile errors
* Add analyzer package reference and ruleset to csproj to support IDE

I'm still considering which analyzer to use. (`ErrorProne.NET.CoreAnalyzers` may be supported in the first release.)
https://github.com/Cybermaxs/awesome-analyzers#analyzers

Please tell me if you have any suggestions. :)

**Comment by KuraiAndras** [comment]
Well, I have been using https://github.com/tertle/com.bovinelabs.analyzers for this, and most of the time I'm satisfied by this. The only problem I see is that this, bovinelabs and the unity provided solutions are not that great because you will have to manually download dlls, commit them to source control and after some time manually update them.  
What would be nice is have the ability to just reference analyzers as nuget packages (the way they were intended to be used), but right now with unity doing this is hard. It could be done with something like my project: https://github.com/KuraiAndras/UnityCsprojNuget in the created csproj file you can reference the analyzer packages as explicit dependencies, so when building the .net framework project the dlls will be in the bin directory, so they can be referenced by unity. But this solution is also hacky, and error prone

Also this could be a rabbit hole if you want to support common scenarios for analyzers:
- .editorconfig files should also be respected (not sure if they are picked up by the unity build pipeline)
- Analyzer settings can also be added to csproj files now, but since they are regenerated every time some csproj asset post processor is needed
- Updating / maintaining analyzer dlls without a csproj will be error prone, and a pain in the ass

**Comment by mob-sakai** [comment]
Thanks for the suggestion. :+1:

**Comment by KuraiAndras** [comment]
So similarly how the compiler toolchain is specified by name and version in the project settings, you will be able to add them through the project settings?

**Comment by mob-sakai** [comment]
Maybe, yes.

**Comment by mob-sakai** [comment]
WIP: It seems to be working fine.

![](https://user-images.githubusercontent.com/12690315/99017422-36886880-259b-11eb-9c39-21786a767e6d.png)
![](https://user-images.githubusercontent.com/12690315/99017608-aac30c00-259b-11eb-9be4-7d5c8607812a.png)

**Comment by mob-sakai** [comment]
WIP: It is available from the develop branch.

```
{
  "dependencies": {
    "com.coffee.csharp-compiler-settings": "https://github.com/mob-sakai/CSharpCompilerSettingsForUnity.git#develop",
    ...
  },
}
```

![](https://user-images.githubusercontent.com/12690315/99193353-ce649d00-27bb-11eb-9682-64952d0ac82b.png)

* Support `ErrorProne.NET.CoreAnalyzers`, `Roslynator` and `StyleCop.Analyzers` as **preset analyzer packages**.
  * **Edit:** You can enter non-preset analysis packages directly into the text field.  
![](https://user-images.githubusercontent.com/12690315/99193479-87c37280-27bc-11eb-890e-9063e2178bca.png)
* Include/exclude assemblies to analyze.  
![](https://user-images.githubusercontent.com/12690315/99193475-8134fb00-27bc-11eb-81e2-567a1e2a90f8.png)

**Comment by KuraiAndras** [comment]
A few other analyzers which might be useful:

https://github.com/cezarypiatek/MappingGenerator

(SonarQube is widely used by large organizations so adding this would be nice)
https://github.com/SonarSource/sonar-dotnet

https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/
https://www.nuget.org/packages/Microsoft.VisualStudio.Threading.Analyzers/
https://www.nuget.org/packages/Roslyn.Analyzers/
https://www.nuget.org/packages/Meziantou.Analyzer/
https://www.nuget.org/packages/Asyncify/
https://www.nuget.org/packages/AsyncFixer

https://www.nuget.org/packages/ClrHeapAllocationAnalyzer/

Also, from this it seems the library will need to be updated to add new analyzers. Can you create a contribution guide on how to add new ones?
Also will .editorconfig files be picked up by the compiler?

**Comment by mob-sakai** [comment]
> Also, from this it seems the library will need to be updated to add new analyzers.

You can enter non-preset analysis packages directly into the text field.

> Can you create a contribution guide on how to add new ones?

👍 

> Also will .editorconfig files be picked up by the compiler?

Yes, I ~will add~ have added `analyzerconfig` option into response file.
`{project_dir}/.editorconfig` and `{asmdef_dir}/.editorconfig` will be picked up.

**Comment by mob-sakai** [comment]
To be honest, I don't know much about analyzer packages... lol

**Comment by KuraiAndras** [comment]
You should add support multiple .editoconfigs if that is possible. It is a common scenario to have nested editorconfigs. For example when you must use unity packages, I tend to place a .editorconfig next to them with: 
```
[*.cs]
generated_code = true
``` 
Which will turn off all analysis for the files under it.
